version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    restart: 'on-failure'
    environment:
      - BOT_URL
      - ASPNETCORE_ENVIRONMENT
    #      - DB_CONNECTION_STRING
    networks:
      - proxy
    # Traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=${TRAEFIK_HOST}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Cache-Control=no-cache"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Pragma=no-cache"

networks:
  proxy:
    external: true